### ISSUE TITLE
AssertionError on running swat-s1

### ISSUE THREAD

**Issue by donadelden** [scy-phy/minicps#29]
Hello,
I am facing an issue when running `swat-s1` after having uncommented the lines of code that enable all the plc functionalities (lines 45-46 of `plc2.py` and 92-104 of `plc1.py`). After a while, the simulations stops and the logs of each plc return an exception:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
  "__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  exec code in run_globals
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1699, in <module>
  sys.exit( main() )
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1680, in main
  fragment=fragment, printing=printing, timeout=timeout )
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1444, in process
  transactions		= list( self.results( operations=operations, **kwds ))
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1436, in results
  for idx,dsc,req,rpy,sts,val in self.operate( operations, **kwds ):
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1431, in operate
  for idx,dsc,req,rpy,sts,val in harvested:
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1321, in validate
  for index,descr,request,reply,status,val in harvested:
File "/usr/local/lib/python2.7/dist-packages/cpppo/server/enip/client.py", line 1308, in pipeline
  complete, requests )
AssertionError: Communication ceased before harvesting all pipeline responses:   0/  1`  
```

It is possible to reproduce this behavior with cpppo==4.0.4 or cpppo==4.3.4 and probably other versions, while more recent versions (like 4.4) cannot be used due to another error (addressed here #28). 

Furthermore, I notice that the exception arise always after a specific period. To check it, I attach a version of [`physical_process.py`](https://github.com/scy-phy/minicps/files/6206826/physical_process.zip) that writes in a csv file (`out.csv`)
 a log of each variable and a timestamp at every cycle. Exceptions arises always at timestamp = 88.40.  

I'm working on Ubuntu 20.04, but I tried in other versions as well without any luck. 

Is there any solution to this behavior? Thank you!

**Comment by noleti** [comment]
Sorry for the delayed response. I tried to reproduce this issue now and don't see it locally. This might be related to a minor change I am going to push soon which changes the way hosts log to files (c336ed2). If this is still relevant, please test with that/ the upcoming experimental python3 release.

I actually like your proposed csv logging for the process in the example. I will add it to the example. Please shout if you do not agree with this.
